# Generated by Django 4.1 on 2022-08-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_profile.jpg', upload_to='profile_pics', verbose_name='profile picture'),
        ),
    ]
