# Generated by Django 4.1 on 2022-08-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default_profile.jpg', upload_to='profile_pics/users', verbose_name='profile picture'),
        ),
    ]
