# Generated by Django 4.1 on 2022-08-23 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='random_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
