# Generated by Django 4.1 on 2022-08-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_random_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='random_uuid',
        ),
    ]
