# Generated by Django 4.1 on 2022-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profile_random_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delete_number',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
