# Generated by Django 4.1 on 2022-08-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_created_on_alter_todo_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dead_line',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
