# Generated by Django 4.1 on 2022-09-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_on']},
        ),
    ]
