# Generated by Django 4.1 on 2022-09-06 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0006_alter_comment_options_alter_todo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_in', to='todo.todo'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
